## Jekyll configs
markdown: rdiscount
permalink: /:year/:month/:day/:title/
highlighter: pygments
rdiscount:
  extensions: [smart]
sass:
  style: :compressed
gems:
  - jekyll-sitemap

## Site structure
collections:
  testimonials:
    output: true
    permalink: /testimonials/:title/
  sections:
    output: false
    permalink: /:title/

defaults:
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: "testimonial"

## Basic company info
title: Company
primary_author: "Company, Inc."
shortname: Comp
tagline: "Serving ours customers' needs"
offering: "Business and corporate services"
offer_description: "We do a lot of stuff. This is a lengthy paragraph of text."

## Site and contact bits
baseurl: "http://www.example.com"
# subpath should include leading slash or be an empty string
subpath: '/jekyll-brochure'
source_repo: http://www.github.com/ao5357/jekyll-brochure
email: ao5357@gmail.com 
phone: (555) 555-1234
phonedigits: "5555551234"
# gaid: UA-697953-3

## schema.org type (default for site, often "Website")
schema: LocalBusiness

## Open Graph
og_street_address: 123 Fake St
og_locality: Noncity
og_region: MI
og_postal_code: "48888"
og_country: USA

## Social links
social:
  -
    title: Facebook
    url: https://www.facebook.com/buyexamplebusiness
  -
    title: Twitter
    url: https://twitter.com/example

## Colors
# Secondary especially should not be a regular blue
# Text should be close to black, but not black (or dark gray)
# Light is typically #fff, but could be a non-white very light tint
colors:
  primary: "#014"
  secondary: "#f41"
  tertiary: "#7c1"
  quarternary: "#04f"
  text: "#002"
  light: "#fff"
